version: "3.9"
services:
  web:
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1 # hot reload
    command: >
      sh -c "flask db upgrade; flask run --host 0.0.0.0 --port 5000"
