version: "3.9"
services:
  web:
    build:
      context: .
    ports:
      - 5001:95
    container_name: retailradartrends-api
    networks:
      - nginx-proxy-manager_default
    restart: always
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
    command: >
      sh -c "flask db upgrade && gunicorn --bind 0.0.0.0:95 'app:create_app()'"

networks:
  nginx-proxy-manager_default:
    external: true
